# docker compose up --detach --build --force-recreate --remove-orphans

name: node
services:
    application:
        image: application
        container_name: application
        depends_on:
            - mongo
            - mongo-admin
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "4000:3000"
        environment:
            - MONGODB_URL=mongodb://admin:password@mongo:27017/node?authSource=admin
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
    mongo-admin:
        image: mongo-express
        container_name: mongo-admin
        depends_on:
            - mongo
        ports:
            - "27018:8081"
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH: false
