name: node
services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - ~/volumes/mongo:/data/db
    mongo-ui:
        image: mongo-express
        container_name: mongo-ui
        restart: always
        depends_on:
            - mongo
        ports:
            - "27018:8081"
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=password
